apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: manifest
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/pasika-swn/prod-k8s-manifests2.git
   targetRevision: main
   path: nongkai
   directory: 
      recurse: true
 destination:
   server: https://kubernetes.default.svc
