apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: idp-app
 namespace: argocd
spec:
 project: default
 source:
   repoURL: git@github.com:pasika-swn/prod-k8s-manifests2.git
   targetRevision: main
   path: pedjeab/cart
   directory: 
      recurse: true
 destination:
   server: https://kubernetes.default.svc

