apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: nonprod
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/pasika-swn/nonprod-k8s-manifests.git
   targetRevision: main
   path: dev/pedjeab/cart
   directory: 
      recurse: true
 destination:
   server: https://kubernetes.default.svc
