apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: idp-app
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/pasika-swn/idp-app.git
   targetRevision: main
   path: platform/prod
   directory: 
      recurse: true
 destination:
   server: https://kubernetes.default.svc